// packages/library/src/components/data-display/KeyboardKey/index.vue
<script lang="ts">
import type {
  KeyboardKeyFormat,
  KeyboardKeyPlatform,
  KeyboardKeySize,
} from './keyboard-key.shared';

export interface KeyboardKeyProps {
  /** Klawisz albo uporządkowana kombinacja tokenów. String rozdziela tokeny znakiem plus. */
  keys: string | readonly string[];
  /** Platforma używana do mapowania przenośnego tokenu Mod i symboli modyfikatorów. */
  platform?: KeyboardKeyPlatform;
  /** Symbole skracają zapis wizualny; pełne nazwy pozostają dostępne dla AT. */
  format?: KeyboardKeyFormat;
  /** Rozmiar keycapów zgodny ze skalą kompaktowych komponentów PeaUI. */
  size?: KeyboardKeySize;
  /** Wariant inline dopasowuje komponent do wiersza tekstu; false tworzy osobny blok. */
  inline?: boolean;
  /** Wyłącznie wizualny separator kolejnych klawiszy. */
  separator?: string;
  /** Pełna dostępna nazwa zastępująca automatycznie złożoną frazę. */
  ariaLabel?: string;
  /** Ogranicza kontrast nieaktywnej wizualnie wskazówki bez dodawania semantyki disabled. */
  muted?: boolean;
  /** Stabilny selektor testowy elementu głównego. */
  dataTestId?: string;
}

export type {
  KeyboardKeyFormat,
  KeyboardKeyPlatform,
  KeyboardKeySize,
  KeyboardKeySlotState,
  ResolvedKeyboardKeyPlatform,
} from './keyboard-key.shared';
</script>

<script setup lang="ts">
import { UIKIT_NAME } from '@/constants';
import { computed, onMounted, ref, useAttrs, watch, type CSSProperties } from 'vue';

import {
  createKeyboardKeyAccessibleLabel,
  detectKeyboardPlatform,
  resolveInitialKeyboardPlatform,
  resolveKeyboardKeyCombination,
  type KeyboardKeySlotState,
  type ResolvedKeyboardKeyPlatform,
} from './keyboard-key.shared';

defineOptions({ inheritAttrs: false });

const props = withDefaults(defineProps<KeyboardKeyProps>(), {
  platform: 'auto',
  format: 'symbol',
  size: 's',
  inline: true,
  separator: '+',
  ariaLabel: '',
  muted: false,
});

const slots = defineSlots<{
  key?: (state: KeyboardKeySlotState) => unknown;
  separator?: (state: { index: number; separator: string }) => unknown;
}>();

const attrs = useAttrs();
const root = `${UIKIT_NAME}-keyboard-key`;
const mounted = ref(false);
const detectedPlatform = ref<ResolvedKeyboardKeyPlatform>('generic');

const resolvedPlatform = computed<ResolvedKeyboardKeyPlatform>(() =>
  props.platform === 'auto' ? detectedPlatform.value : props.platform,
);
const states = computed(() =>
  resolveKeyboardKeyCombination(props.keys, resolvedPlatform.value, props.format),
);
const accessibleLabel = computed(() =>
  createKeyboardKeyAccessibleLabel(
    states.value,
    normalizeAttribute(attrs['aria-label']) ?? props.ariaLabel,
  ),
);
const rootClasses = computed(() => [
  root,
  `${root}--${props.inline ? 'inline' : 'block'}`,
  `${root}--size-${props.size}`,
  props.muted && `${root}--muted`,
  attrs.class,
]);
const rootStyle = computed(() => attrs.style as CSSProperties | undefined);
const rootAttrs = computed(() => {
  const {
    class: _class,
    style: _style,
    role: _role,
    tabindex: _tabindex,
    'aria-label': _ariaLabel,
    'aria-keyshortcuts': _ariaKeyshortcuts,
    ...rest
  } = attrs;
  return rest;
});

function normalizeAttribute(value: unknown): string | undefined {
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function detectClientPlatform(): ResolvedKeyboardKeyPlatform {
  if (typeof navigator === 'undefined') return 'generic';
  return detectKeyboardPlatform(navigator.userAgent, navigator.platform);
}

watch(
  () => props.platform,
  (platform) => {
    detectedPlatform.value =
      platform === 'auto' && mounted.value
        ? detectClientPlatform()
        : resolveInitialKeyboardPlatform(platform);
  },
  { immediate: true },
);

onMounted(() => {
  mounted.value = true;
  if (props.platform === 'auto') detectedPlatform.value = detectClientPlatform();
});
</script>

<template>
  <span
    v-bind="rootAttrs"
    :class="rootClasses"
    :style="rootStyle"
    :data-format="format"
    :data-inline="inline || undefined"
    :data-muted="muted || undefined"
    :data-platform="resolvedPlatform"
    :data-testid="dataTestId"
  >
    <span :class="`${root}__accessible`">{{ accessibleLabel }}</span>
    <span :class="`${root}__visual`" aria-hidden="true">
      <kbd v-if="states[0]" :class="`${root}__key`" :data-key="states[0].key">
        <slot v-if="slots.key" name="key" v-bind="states[0]" />
        <template v-else>{{ states[0].visualLabel }}</template>
      </kbd>
      <span
        v-for="state in states.slice(1)"
        :key="`${state.index}-${state.token}`"
        :class="`${root}__segment`"
      >
        <span :class="`${root}__separator`">
          <slot v-if="slots.separator" name="separator" :index="state.index" :separator />
          <template v-else>{{ separator }}</template>
        </span>
        <kbd :class="`${root}__key`" :data-key="state.key">
          <slot v-if="slots.key" name="key" v-bind="state" />
          <template v-else>{{ state.visualLabel }}</template>
        </kbd>
      </span>
    </span>
  </span>
</template>

// packages/library/src/components/data-display/KeyboardKey/index.tsx
/** @jsxImportSource react */
import {
  forwardRef,
  useEffect,
  useMemo,
  useState,
  type CSSProperties,
  type HTMLAttributes,
  type ReactElement,
  type ReactNode,
} from 'react';

import {
  createKeyboardKeyAccessibleLabel,
  detectKeyboardPlatform,
  resolveKeyboardKeyCombination,
  type KeyboardKeyFormat,
  type KeyboardKeyPlatform,
  type KeyboardKeySize,
  type KeyboardKeySlotState,
  type ResolvedKeyboardKeyPlatform,
} from './keyboard-key.shared';

export type KeyboardKeyProps = Omit<
  HTMLAttributes<HTMLSpanElement>,
  'aria-keyshortcuts' | 'aria-label' | 'children' | 'role' | 'size' | 'tabIndex'
> & {
  keys: string | readonly string[];
  platform?: KeyboardKeyPlatform;
  format?: KeyboardKeyFormat;
  size?: KeyboardKeySize;
  inline?: boolean;
  separator?: string;
  ariaLabel?: string;
  muted?: boolean;
  dataTestId?: string;
  renderKey?: (state: KeyboardKeySlotState) => ReactNode;
  renderSeparator?: (state: { index: number; separator: string }) => ReactNode;
};

export type {
  KeyboardKeyFormat,
  KeyboardKeyPlatform,
  KeyboardKeySize,
  KeyboardKeySlotState,
  ResolvedKeyboardKeyPlatform,
} from './keyboard-key.shared';

function detectClientPlatform(): ResolvedKeyboardKeyPlatform {
  if (typeof navigator === 'undefined') return 'generic';
  return detectKeyboardPlatform(navigator.userAgent, navigator.platform);
}

const KeyboardKey = forwardRef<HTMLSpanElement, KeyboardKeyProps>(function KeyboardKey(
  {
    keys,
    platform = 'auto',
    format = 'symbol',
    size = 's',
    inline = true,
    separator = '+',
    ariaLabel = '',
    muted = false,
    dataTestId,
    renderKey,
    renderSeparator,
    className,
    style,
    ...rest
  },
  ref,
): ReactElement {
  const [detectedPlatform, setDetectedPlatform] = useState<ResolvedKeyboardKeyPlatform>('generic');
  const resolvedPlatform = platform === 'auto' ? detectedPlatform : platform;
  const states = useMemo(
    () => resolveKeyboardKeyCombination(keys, resolvedPlatform, format),
    [format, keys, resolvedPlatform],
  );
  const accessibleLabel = createKeyboardKeyAccessibleLabel(states, ariaLabel);
  const resolvedTestId =
    dataTestId ??
    (rest as HTMLAttributes<HTMLSpanElement> & { 'data-testid'?: string })['data-testid'];
  const classes = [
    'peaui-keyboard-key',
    `peaui-keyboard-key--${inline ? 'inline' : 'block'}`,
    `peaui-keyboard-key--size-${size}`,
    muted && 'peaui-keyboard-key--muted',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  useEffect(() => {
    setDetectedPlatform(platform === 'auto' ? detectClientPlatform() : platform);
  }, [platform]);

  const renderKeycap = (state: KeyboardKeySlotState): ReactElement => (
    <kbd className="peaui-keyboard-key__key" data-key={state.key}>
      {renderKey?.(state) ?? state.visualLabel}
    </kbd>
  );

  return (
    <span
      {...rest}
      ref={ref}
      className={classes}
      style={style as CSSProperties}
      data-format={format}
      data-inline={inline || undefined}
      data-muted={muted || undefined}
      data-platform={resolvedPlatform}
      data-testid={resolvedTestId}
    >
      <span className="peaui-keyboard-key__accessible">{accessibleLabel}</span>
      <span className="peaui-keyboard-key__visual" aria-hidden="true">
        {states[0] ? renderKeycap(states[0]) : null}
        {states.slice(1).map((state) => (
          <span className="peaui-keyboard-key__segment" key={`${state.index}-${state.token}`}>
            <span className="peaui-keyboard-key__separator">
              {renderSeparator?.({ index: state.index, separator }) ?? separator}
            </span>
            {renderKeycap(state)}
          </span>
        ))}
      </span>
    </span>
  );
});

KeyboardKey.displayName = 'KeyboardKey';

export default KeyboardKey;
